let subjectTitle = "Object Oriented Programming"
let classSchedule = "4:00-5:00 in Monday and Friday"
let classroom = "Computer Laboratory C"
let classInstructor = "Mr. Ryan Jay Cuevas"
let studentName = "Heleina Paula G. Molina"